#端口
server:
  port: 8110

spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.26.161.253:3306/myapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
